/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ECSE321.EventRegistration;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
